tunnel: f482af46-dfd3-467d-b0c5-c11c47958512
credentials-file: /etc/cloudflared/f482af46-dfd3-467d-b0c5-c11c47958512.json

ingress:
  - hostname: ncc.hacksters.tech
    service: http://frontend:3000
  - service: http_status:404
