tunnel: f482af46-dfd3-467d-b0c5-c11c47958512
credentials-file: /etc/cloudflared/f482af46-dfd3-467d-b0c5-c11c47958512.json

ingress:
  - hostname: ncc.hacksters.tech
    service: http://127.0.0.1:80
  - hostname: dbncc.hacksters.tech
    service: http://127.0.0.1:8080    
  - service: http_status:404
